CREATE TABLE IF NOT EXISTS bonilla_routes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  localidad VARCHAR(120) NULL,
  notes TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE bonilla_clients ADD COLUMN route_id INT UNSIGNED NULL;
ALTER TABLE bonilla_clients ADD INDEX idx_route_id (route_id);
